### ISSUE TITLE
feat(vscode/client): loader during prep

### ISSUE THREAD

**Issue by ShaunSHamilton** [freeCodeCamp/external-project#43]

**Comment by ShaunSHamilton** [comment]
@moT01 Could you outline what you were thinking here, please?

**Comment by moT01** [comment]
Not really sure on the loader, but when I run course, the simple browser opens with a white screen while everything installs - which can take a decent amount of time. I dunno, I would have to play with - could we somehow load a static index.html file with a css loader until the server starts? Then redirect to that or something. That's all that comes to mind at the moment.

**Comment by ShaunSHamilton** [comment]
> could we somehow load a static index.html file with a css loader until the server starts? 

@moT01 Yes. Quite easily. I will try to get something out, and you can comment specific implementation on the PR.
