### ISSUE TITLE
[FEAT] Add `beforeAll` and `beforeEach` scripts

### ISSUE THREAD

**Issue by ShaunSHamilton** [freeCodeCamp/external-project#81]
Syntax:

````markdown
...

### --tests--
...

### --before-all--

```js
// Clear test cache from previous run
```

### --before-each--

```js
// Helps DRY code
```
````

@moT01 Anything I might be forgetting here?

_I have marked this as 'priority: high' because I need it for the integrated projects_

**Comment by moT01** [comment]
Not that I need or can think of at the moment
